import type { DishPriority, PriceLevel } from "@/types/restaurant";
import { generatedRestaurants } from "./generated";

/**
 * Hand-authored demo dataset covering Irvine, Costa Mesa, Newport Beach,
 * Little Tokyo, Koreatown, and Downtown LA. This is the single source of
 * truth for:
 *  - `providers/mock.ts` (live nearby search when no real API keys exist)
 *  - `db/seed/seed.ts` (populates Neon with restaurants + demo visits/journal)
 *
 * Ratings/review counts here are fabricated for demo purposes — they are
 * replaced by live provider data once GOOGLE_PLACES_API_KEY / YELP_API_KEY
 * are configured (see /providers/index.ts).
 */

export interface MockDish {
  name: string;
  description: string;
  estimatedPrice: number;
  spiceLevel: 0 | 1 | 2 | 3;
  dietaryTags?: string[];
  priority: DishPriority;
  whyOrder: string;
}

export interface MockSource {
  provider: "google" | "yelp" | "foursquare";
  rating: number;
  ratingScale: number;
  ratingCount: number;
}

export interface MockRestaurantSeed {
  id: string;
  name: string;
  latitude: number;
  longitude: number;
  address: string;
  city: string;
  neighborhood: string;
  zip: string;
  cuisines: string[];
  priceLevel: PriceLevel;
  phone: string;
  website?: string;
  openingHours: Record<string, string>;
  photoSeeds: string[]; // used to build deterministic picsum.photos URLs
  dishes: MockDish[];
  sources: MockSource[];
  popularityScore: number; // 0-100, seeds trending/popularity demo
}

const HOURS_STANDARD = {
  mon: "11:00 AM - 9:00 PM",
  tue: "11:00 AM - 9:00 PM",
  wed: "11:00 AM - 9:00 PM",
  thu: "11:00 AM - 9:00 PM",
  fri: "11:00 AM - 10:00 PM",
  sat: "11:00 AM - 10:00 PM",
  sun: "11:00 AM - 9:00 PM",
};

const HOURS_LATE = {
  mon: "11:30 AM - 12:00 AM",
  tue: "11:30 AM - 12:00 AM",
  wed: "11:30 AM - 12:00 AM",
  thu: "11:30 AM - 1:00 AM",
  fri: "11:30 AM - 2:00 AM",
  sat: "11:30 AM - 2:00 AM",
  sun: "11:30 AM - 12:00 AM",
};

const HOURS_CAFE = {
  mon: "7:00 AM - 6:00 PM",
  tue: "7:00 AM - 6:00 PM",
  wed: "7:00 AM - 6:00 PM",
  thu: "7:00 AM - 6:00 PM",
  fri: "7:00 AM - 8:00 PM",
  sat: "8:00 AM - 8:00 PM",
  sun: "8:00 AM - 6:00 PM",
};

function photos(seed: string, count = 3) {
  return Array.from({ length: count }, (_, i) => `bitemap-${seed}-${i}`);
}

const handCraftedRestaurants: MockRestaurantSeed[] = [
  // ---------------------------------------------------------------- Irvine
  {
    id: "din-tai-fung-irvine",
    name: "Din Tai Fung",
    latitude: 33.6606,
    longitude: -117.7459,
    address: "3988 Barranca Pkwy, Irvine, CA",
    city: "Irvine",
    neighborhood: "Irvine Spectrum",
    zip: "92606",
    cuisines: ["Chinese", "Taiwanese", "Dim Sum"],
    priceLevel: "$$",
    phone: "(714) 838-9868",
    website: "https://dintaifungusa.com",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("dtf"),
    dishes: [
      {
        name: "Xiao Long Bao",
        description: "Steamed pork soup dumplings, 10 to an order.",
        estimatedPrice: 12.5,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "The dish the entire restaurant is built around — order it first.",
      },
      {
        name: "Spicy Wontons",
        description: "Pork wontons in chili oil and garlic sauce.",
        estimatedPrice: 9.5,
        spiceLevel: 2,
        priority: "popular",
        whyOrder: "The most-ordered appetizer after the XLB.",
      },
      {
        name: "String Beans",
        description: "Sautéed string beans with garlic.",
        estimatedPrice: 11,
        spiceLevel: 0,
        dietaryTags: ["vegetarian"],
        priority: "best_value",
        whyOrder: "Balances the richness of the dumplings.",
      },
      {
        name: "Pork Chop Fried Rice",
        description: "Fried rice topped with a fried pork chop.",
        estimatedPrice: 16,
        spiceLevel: 0,
        priority: "staff_favorite",
        whyOrder: "A heartier plate if you're not just doing small plates.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.6, ratingScale: 5, ratingCount: 8420 },
      { provider: "yelp", rating: 4.3, ratingScale: 5, ratingCount: 3210 },
      { provider: "foursquare", rating: 9.1, ratingScale: 10, ratingCount: 640 },
    ],
    popularityScore: 96,
  },
  {
    id: "hironori-irvine",
    name: "HiroNori Craft Ramen",
    latitude: 33.6839,
    longitude: -117.8078,
    address: "2700 Alton Pkwy, Irvine, CA",
    city: "Irvine",
    neighborhood: "Great Park",
    zip: "92606",
    cuisines: ["Japanese", "Ramen"],
    priceLevel: "$$",
    phone: "(949) 385-5088",
    website: "https://hironoriramen.com",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("hironori"),
    dishes: [
      {
        name: "Tonkotsu Ramen",
        description: "18-hour pork bone broth, thin noodles, chashu.",
        estimatedPrice: 15,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "The house specialty and reason for the always-long line.",
      },
      {
        name: "Pork Buns",
        description: "Steamed bao with braised pork belly.",
        estimatedPrice: 8,
        spiceLevel: 0,
        priority: "popular",
        whyOrder: "Perfect starter while you wait for the ramen.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.7, ratingScale: 5, ratingCount: 2140 },
      { provider: "yelp", rating: 4.4, ratingScale: 5, ratingCount: 1580 },
    ],
    popularityScore: 89,
  },
  {
    id: "shik-do-rak-irvine",
    name: "Shik Do Rak",
    latitude: 33.6712,
    longitude: -117.8092,
    address: "14400 Culver Dr, Irvine, CA",
    city: "Irvine",
    neighborhood: "Culver Plaza",
    zip: "92604",
    cuisines: ["Korean", "Korean BBQ"],
    priceLevel: "$$$",
    phone: "(949) 654-4444",
    openingHours: HOURS_LATE,
    photoSeeds: photos("shikdorak"),
    dishes: [
      {
        name: "Prime Galbi",
        description: "Marinated prime beef short rib, grilled tableside.",
        estimatedPrice: 42,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "Consistently the highest-rated cut on the menu.",
      },
      {
        name: "Kimchi Jjigae",
        description: "Kimchi stew with pork belly and tofu.",
        estimatedPrice: 19,
        spiceLevel: 2,
        priority: "local_favorite",
        whyOrder: "A cozy, comforting way to end a BBQ dinner.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.5, ratingScale: 5, ratingCount: 1890 },
      { provider: "yelp", rating: 4.2, ratingScale: 5, ratingCount: 990 },
    ],
    popularityScore: 78,
  },
  {
    id: "cafe-hibiscus-irvine",
    name: "Cafe Hibiscus",
    latitude: 33.6578,
    longitude: -117.7301,
    address: "2700 Alton Pkwy Suite 115, Irvine, CA",
    city: "Irvine",
    neighborhood: "Irvine Spectrum",
    zip: "92618",
    cuisines: ["Vietnamese", "Cafe"],
    priceLevel: "$",
    phone: "(949) 715-2288",
    openingHours: HOURS_CAFE,
    photoSeeds: photos("hibiscus"),
    dishes: [
      {
        name: "Vietnamese Iced Coffee",
        description: "Robusta coffee over condensed milk and ice.",
        estimatedPrice: 5.5,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "The house draw — strong, sweet, and worth the trip alone.",
      },
      {
        name: "Bánh Mì Thịt",
        description: "Grilled pork banh mi with pickled daikon and carrot.",
        estimatedPrice: 9,
        spiceLevel: 1,
        priority: "best_value",
        whyOrder: "Best-value lunch on this side of Irvine.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.4, ratingScale: 5, ratingCount: 620 },
      { provider: "yelp", rating: 4.1, ratingScale: 5, ratingCount: 310 },
    ],
    popularityScore: 61,
  },
  {
    id: "tokyo-table-irvine",
    name: "Tokyo Table",
    latitude: 33.6851,
    longitude: -117.8231,
    address: "71 Fortune Dr, Irvine, CA",
    city: "Irvine",
    neighborhood: "Diamond Jamboree",
    zip: "92618",
    cuisines: ["Japanese", "Izakaya", "Sushi"],
    priceLevel: "$$",
    phone: "(949) 502-6688",
    openingHours: HOURS_LATE,
    photoSeeds: photos("tokyotable"),
    dishes: [
      {
        name: "Salmon Aburi Sushi",
        description: "Torched salmon nigiri, 4 pieces.",
        estimatedPrice: 14,
        spiceLevel: 0,
        priority: "popular",
        whyOrder: "Their most-photographed dish for good reason.",
      },
      {
        name: "Karaage",
        description: "Japanese fried chicken thigh, served with kewpie mayo.",
        estimatedPrice: 11,
        spiceLevel: 1,
        priority: "safe_pick",
        whyOrder: "Reliable crowd-pleaser to start the table.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.3, ratingScale: 5, ratingCount: 1120 },
      { provider: "yelp", rating: 4.0, ratingScale: 5, ratingCount: 640 },
    ],
    popularityScore: 70,
  },
  {
    id: "kura-revolving-irvine",
    name: "Kura Revolving Sushi Bar",
    latitude: 33.6621,
    longitude: -117.7472,
    address: "13782 Jamboree Rd, Irvine, CA",
    city: "Irvine",
    neighborhood: "Irvine Spectrum",
    zip: "92620",
    cuisines: ["Japanese", "Sushi"],
    priceLevel: "$",
    phone: "(949) 786-6688",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("kura"),
    dishes: [
      {
        name: "Negitoro Hand Roll",
        description: "Chopped fatty tuna and scallion hand roll.",
        estimatedPrice: 3.5,
        spiceLevel: 0,
        priority: "best_value",
        whyOrder: "Best price-to-quality plate on the belt.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.2, ratingScale: 5, ratingCount: 2460 },
      { provider: "yelp", rating: 3.9, ratingScale: 5, ratingCount: 1340 },
    ],
    popularityScore: 74,
  },
  {
    id: "bosscat-irvine",
    name: "Bosscat Kitchen & Libations",
    latitude: 33.6577,
    longitude: -117.7423,
    address: "13590 Jamboree Rd, Irvine, CA",
    city: "Irvine",
    neighborhood: "Irvine Spectrum",
    zip: "92620",
    cuisines: ["American", "Comfort Food"],
    priceLevel: "$$$",
    phone: "(949) 216-6480",
    openingHours: HOURS_LATE,
    photoSeeds: photos("bosscat"),
    dishes: [
      {
        name: "Fried Chicken Biscuit Sandwich",
        description: "Buttermilk fried chicken, honey butter, brioche.",
        estimatedPrice: 18,
        spiceLevel: 1,
        priority: "must_try",
        whyOrder: "Their most-ordered plate at brunch and dinner alike.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.4, ratingScale: 5, ratingCount: 1780 },
      { provider: "yelp", rating: 4.1, ratingScale: 5, ratingCount: 890 },
    ],
    popularityScore: 68,
  },
  {
    id: "curry-house-irvine",
    name: "Curry House CoCo Ichibanya",
    latitude: 33.6862,
    longitude: -117.8241,
    address: "2700 Jamboree Rd, Irvine, CA",
    city: "Irvine",
    neighborhood: "Diamond Jamboree",
    zip: "92618",
    cuisines: ["Japanese", "Curry"],
    priceLevel: "$",
    phone: "(949) 861-2622",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("cocoichi"),
    dishes: [
      {
        name: "Katsu Curry",
        description: "Japanese curry rice topped with breaded pork cutlet.",
        estimatedPrice: 13,
        spiceLevel: 1,
        priority: "safe_pick",
        whyOrder: "Fully customizable spice level, 1 to 10.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.3, ratingScale: 5, ratingCount: 980 },
      { provider: "yelp", rating: 4.0, ratingScale: 5, ratingCount: 470 },
    ],
    popularityScore: 58,
  },
  {
    id: "85c-bakery-irvine",
    name: "85°C Bakery Cafe",
    latitude: 33.6845,
    longitude: -117.8103,
    address: "2700 Alton Pkwy, Irvine, CA",
    city: "Irvine",
    neighborhood: "Great Park",
    zip: "92606",
    cuisines: ["Taiwanese", "Bakery", "Dessert", "Cafe"],
    priceLevel: "$",
    phone: "(949) 786-1885",
    openingHours: HOURS_LATE,
    photoSeeds: photos("85c"),
    dishes: [
      {
        name: "Sea Salt Coffee",
        description: "Cold brew topped with sea salt cream foam.",
        estimatedPrice: 4.75,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "The drink that put this chain on the map.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.3, ratingScale: 5, ratingCount: 1540 },
      { provider: "yelp", rating: 4.0, ratingScale: 5, ratingCount: 720 },
    ],
    popularityScore: 64,
  },
  {
    id: "sate-thai-irvine",
    name: "Sate Thai Cuisine",
    latitude: 33.6499,
    longitude: -117.7075,
    address: "4515 Campus Dr, Irvine, CA",
    city: "Irvine",
    neighborhood: "University Park",
    zip: "92612",
    cuisines: ["Thai"],
    priceLevel: "$$",
    phone: "(949) 725-9993",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("sate"),
    dishes: [
      {
        name: "Panang Curry",
        description: "Rich peanut curry with your choice of protein.",
        estimatedPrice: 15,
        spiceLevel: 2,
        priority: "popular",
        whyOrder: "The dish regulars order every visit.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.5, ratingScale: 5, ratingCount: 860 },
      { provider: "yelp", rating: 4.3, ratingScale: 5, ratingCount: 520 },
    ],
    popularityScore: 55,
  },

  // ------------------------------------------------------------ Costa Mesa
  {
    id: "gogi-mogo-costa-mesa",
    name: "Gogi Mogo",
    latitude: 33.6906,
    longitude: -117.8862,
    address: "3320 Hyland Ave, Costa Mesa, CA",
    city: "Costa Mesa",
    neighborhood: "South Coast Metro",
    zip: "92626",
    cuisines: ["Korean", "Korean BBQ"],
    priceLevel: "$$",
    phone: "(714) 545-4644",
    openingHours: HOURS_LATE,
    photoSeeds: photos("gogimogo"),
    dishes: [
      {
        name: "Spicy Pork Bulgogi",
        description: "Gochujang-marinated pork, grilled tableside.",
        estimatedPrice: 22,
        spiceLevel: 2,
        priority: "must_try",
        whyOrder: "Their signature plate, order it medium-spicy first visit.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.4, ratingScale: 5, ratingCount: 730 },
      { provider: "yelp", rating: 4.2, ratingScale: 5, ratingCount: 410 },
    ],
    popularityScore: 60,
  },
  {
    id: "taco-maria-costa-mesa",
    name: "Taco María",
    latitude: 33.6746,
    longitude: -117.8967,
    address: "3313 Hyland Ave, Costa Mesa, CA",
    city: "Costa Mesa",
    neighborhood: "South Coast Collection",
    zip: "92626",
    cuisines: ["Mexican", "Fine Dining"],
    priceLevel: "$$$$",
    phone: "(714) 538-8444",
    website: "https://tacomaria.com",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("tacomaria"),
    dishes: [
      {
        name: "Tasting Menu",
        description: "Chef's seasonal multi-course Alta California tasting menu.",
        estimatedPrice: 145,
        spiceLevel: 1,
        priority: "must_try",
        whyOrder: "Michelin-recognized and the whole reason to book ahead.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.7, ratingScale: 5, ratingCount: 1120 },
      { provider: "yelp", rating: 4.5, ratingScale: 5, ratingCount: 640 },
    ],
    popularityScore: 82,
  },
  {
    id: "pho-79-costa-mesa",
    name: "Pho 79",
    latitude: 33.6798,
    longitude: -117.9151,
    address: "1901 Newport Blvd, Costa Mesa, CA",
    city: "Costa Mesa",
    neighborhood: "17th Street",
    zip: "92627",
    cuisines: ["Vietnamese"],
    priceLevel: "$",
    phone: "(949) 645-1102",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("pho79"),
    dishes: [
      {
        name: "Pho Dac Biet",
        description: "Beef noodle soup, combination of rare steak, brisket, tendon.",
        estimatedPrice: 13,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "The full classic bowl — everything the house does well.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.4, ratingScale: 5, ratingCount: 1980 },
      { provider: "yelp", rating: 4.2, ratingScale: 5, ratingCount: 1240 },
    ],
    popularityScore: 71,
  },
  {
    id: "true-food-kitchen-costa-mesa",
    name: "True Food Kitchen",
    latitude: 33.6912,
    longitude: -117.8871,
    address: "3333 Bristol St, Costa Mesa, CA",
    city: "Costa Mesa",
    neighborhood: "South Coast Plaza",
    zip: "92626",
    cuisines: ["American", "Healthy"],
    priceLevel: "$$$",
    phone: "(714) 384-8090",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("truefood"),
    dishes: [
      {
        name: "Edamame Dumplings",
        description: "Steamed dumplings with miso mustard vinaigrette.",
        estimatedPrice: 14,
        spiceLevel: 0,
        dietaryTags: ["vegetarian"],
        priority: "popular",
        whyOrder: "Consistently the top-ordered starter.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.3, ratingScale: 5, ratingCount: 1450 },
      { provider: "yelp", rating: 4.0, ratingScale: 5, ratingCount: 780 },
    ],
    popularityScore: 62,
  },
  {
    id: "wildfish-costa-mesa",
    name: "Wildfish Seafood Grille",
    latitude: 33.6902,
    longitude: -117.8849,
    address: "1608 Sunflower Ave, Costa Mesa, CA",
    city: "Costa Mesa",
    neighborhood: "South Coast Metro",
    zip: "92626",
    cuisines: ["Seafood", "American", "Fine Dining"],
    priceLevel: "$$$$",
    phone: "(714) 751-3474",
    openingHours: HOURS_LATE,
    photoSeeds: photos("wildfish"),
    dishes: [
      {
        name: "Miso Glazed Sea Bass",
        description: "Chilean sea bass marinated in sweet miso, broiled.",
        estimatedPrice: 48,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "The dish this restaurant is known for across OC.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.5, ratingScale: 5, ratingCount: 2210 },
      { provider: "yelp", rating: 4.3, ratingScale: 5, ratingCount: 1340 },
    ],
    popularityScore: 73,
  },

  // --------------------------------------------------------- Newport Beach
  {
    id: "nobu-newport",
    name: "Nobu Newport Beach",
    latitude: 33.6189,
    longitude: -117.9289,
    address: "445 Newport Center Dr, Newport Beach, CA",
    city: "Newport Beach",
    neighborhood: "Fashion Island",
    zip: "92660",
    cuisines: ["Japanese", "Sushi", "Fine Dining"],
    priceLevel: "$$$$",
    phone: "(949) 759-0708",
    website: "https://noburestaurants.com/newportbeach",
    openingHours: HOURS_LATE,
    photoSeeds: photos("nobu"),
    dishes: [
      {
        name: "Black Cod Miso",
        description: "Miso-marinated black cod, broiled.",
        estimatedPrice: 42,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "Nobu's signature dish worldwide — the benchmark order.",
      },
      {
        name: "Yellowtail Jalapeño",
        description: "Sashimi with jalapeño, yuzu soy.",
        estimatedPrice: 26,
        spiceLevel: 1,
        priority: "popular",
        whyOrder: "The most-ordered starter on every table.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.6, ratingScale: 5, ratingCount: 3120 },
      { provider: "yelp", rating: 4.3, ratingScale: 5, ratingCount: 1680 },
    ],
    popularityScore: 88,
  },
  {
    id: "bear-flag-newport",
    name: "Bear Flag Fish Co.",
    latitude: 33.6067,
    longitude: -117.9298,
    address: "3421 Via Lido, Newport Beach, CA",
    city: "Newport Beach",
    neighborhood: "Lido Marina Village",
    zip: "92663",
    cuisines: ["Seafood", "Cheap Eats"],
    priceLevel: "$$",
    phone: "(949) 673-3474",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("bearflag"),
    dishes: [
      {
        name: "Fish Tacos",
        description: "Grilled or fried fresh catch tacos with cabbage slaw.",
        estimatedPrice: 14,
        spiceLevel: 1,
        priority: "must_try",
        whyOrder: "Frequently voted best fish taco in Orange County.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.5, ratingScale: 5, ratingCount: 1670 },
      { provider: "yelp", rating: 4.3, ratingScale: 5, ratingCount: 980 },
    ],
    popularityScore: 69,
  },
  {
    id: "javier-newport",
    name: "Javier's Newport Beach",
    latitude: 33.6161,
    longitude: -117.9298,
    address: "2891 Newport Blvd, Newport Beach, CA",
    city: "Newport Beach",
    neighborhood: "Cannery Village",
    zip: "92663",
    cuisines: ["Mexican", "Date Night"],
    priceLevel: "$$$",
    phone: "(949) 631-5563",
    openingHours: HOURS_LATE,
    photoSeeds: photos("javiers"),
    dishes: [
      {
        name: "Tableside Guacamole",
        description: "Prepared fresh tableside with your choice of spice.",
        estimatedPrice: 16,
        spiceLevel: 1,
        priority: "popular",
        whyOrder: "The signature opener at every table.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.4, ratingScale: 5, ratingCount: 2340 },
      { provider: "yelp", rating: 4.1, ratingScale: 5, ratingCount: 1120 },
    ],
    popularityScore: 65,
  },
  {
    id: "sushi-roku-newport",
    name: "Sushi Roku",
    latitude: 33.6172,
    longitude: -117.9282,
    address: "401 Newport Center Dr, Newport Beach, CA",
    city: "Newport Beach",
    neighborhood: "Fashion Island",
    zip: "92660",
    cuisines: ["Japanese", "Sushi", "Date Night"],
    priceLevel: "$$$",
    phone: "(949) 640-3474",
    openingHours: HOURS_LATE,
    photoSeeds: photos("sushiroku"),
    dishes: [
      {
        name: "Baked Crab Hand Roll",
        description: "Warm baked crab, spicy mayo, hand-rolled nori.",
        estimatedPrice: 19,
        spiceLevel: 1,
        priority: "must_try",
        whyOrder: "The dish that shows up on every table's photo.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.4, ratingScale: 5, ratingCount: 1560 },
      { provider: "yelp", rating: 4.2, ratingScale: 5, ratingCount: 870 },
    ],
    popularityScore: 66,
  },

  // ------------------------------------------------------------- Little Tokyo
  {
    id: "daikokuya-little-tokyo",
    name: "Daikokuya",
    latitude: 34.0492,
    longitude: -118.2396,
    address: "327 E 1st St, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Little Tokyo",
    zip: "90012",
    cuisines: ["Japanese", "Ramen"],
    priceLevel: "$$",
    phone: "(213) 626-1680",
    openingHours: HOURS_LATE,
    photoSeeds: photos("daikokuya"),
    dishes: [
      {
        name: "Original Ramen",
        description: "Thick, rich tonkotsu-style broth, original since 1984.",
        estimatedPrice: 14,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "One of the restaurants credited with starting LA's ramen boom.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.3, ratingScale: 5, ratingCount: 4560 },
      { provider: "yelp", rating: 4.1, ratingScale: 5, ratingCount: 3980 },
    ],
    popularityScore: 84,
  },
  {
    id: "suehiro-little-tokyo",
    name: "Suehiro Cafe",
    latitude: 34.0489,
    longitude: -118.2401,
    address: "337 E 1st St, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Little Tokyo",
    zip: "90012",
    cuisines: ["Japanese"],
    priceLevel: "$",
    phone: "(213) 626-9132",
    openingHours: HOURS_LATE,
    photoSeeds: photos("suehiro"),
    dishes: [
      {
        name: "Katsu Curry Don",
        description: "Breaded pork cutlet over curry rice, huge portion.",
        estimatedPrice: 15,
        spiceLevel: 1,
        priority: "best_value",
        whyOrder: "Massive portions for the price, a neighborhood staple since 1972.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.3, ratingScale: 5, ratingCount: 1120 },
      { provider: "yelp", rating: 4.2, ratingScale: 5, ratingCount: 890 },
    ],
    popularityScore: 60,
  },
  {
    id: "marugame-monzo-little-tokyo",
    name: "Marugame Monzo",
    latitude: 34.0503,
    longitude: -118.2406,
    address: "329 E 1st St, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Little Tokyo",
    zip: "90012",
    cuisines: ["Japanese", "Udon"],
    priceLevel: "$$",
    phone: "(213) 620-9379",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("marugame"),
    dishes: [
      {
        name: "Uni Cream Udon",
        description: "Hand-made udon in a sea urchin cream sauce.",
        estimatedPrice: 22,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "The reason people wait in line down the block.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.5, ratingScale: 5, ratingCount: 2340 },
      { provider: "yelp", rating: 4.4, ratingScale: 5, ratingCount: 1980 },
    ],
    popularityScore: 87,
  },
  {
    id: "spice-table-little-tokyo",
    name: "The Spice Table",
    latitude: 34.0468,
    longitude: -118.2373,
    address: "114 S Central Ave, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Little Tokyo",
    zip: "90012",
    cuisines: ["Vietnamese", "Singaporean"],
    priceLevel: "$$$",
    phone: "(213) 620-1840",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("spicetable"),
    dishes: [
      {
        name: "Singapore Chili Crab",
        description: "Dungeness crab in sweet-spicy chili sauce, mantou for dipping.",
        estimatedPrice: 58,
        spiceLevel: 2,
        priority: "must_try",
        whyOrder: "A rare LA rendition of the Singaporean classic.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.4, ratingScale: 5, ratingCount: 640 },
      { provider: "yelp", rating: 4.2, ratingScale: 5, ratingCount: 420 },
    ],
    popularityScore: 54,
  },

  // ---------------------------------------------------------------- Koreatown
  {
    id: "kang-ho-dong-ktown",
    name: "Kang Ho-dong Baekjeong",
    latitude: 34.0632,
    longitude: -118.3009,
    address: "3465 W 6th St, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Koreatown",
    zip: "90020",
    cuisines: ["Korean", "Korean BBQ"],
    priceLevel: "$$$",
    phone: "(213) 738-5000",
    openingHours: HOURS_LATE,
    photoSeeds: photos("baekjeong"),
    dishes: [
      {
        name: "Pork Belly Combo",
        description: "Thick-cut pork belly grilled tableside with garlic and scallion.",
        estimatedPrice: 32,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "The dish that made this chain famous across LA.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.4, ratingScale: 5, ratingCount: 5340 },
      { provider: "yelp", rating: 4.1, ratingScale: 5, ratingCount: 3120 },
    ],
    popularityScore: 91,
  },
  {
    id: "sun-nong-dan-ktown",
    name: "Sun Nong Dan",
    latitude: 34.0601,
    longitude: -118.3021,
    address: "3470 W 6th St #C, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Koreatown",
    zip: "90020",
    cuisines: ["Korean"],
    priceLevel: "$$",
    phone: "(213) 380-1113",
    openingHours: HOURS_LATE,
    photoSeeds: photos("sunnongdan"),
    dishes: [
      {
        name: "Galbi Jjim",
        description: "Braised short rib stew with a bubbling cheese-corn topping.",
        estimatedPrice: 45,
        spiceLevel: 1,
        priority: "must_try",
        whyOrder: "Viral for good reason — the cheese pull is real.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.4, ratingScale: 5, ratingCount: 2980 },
      { provider: "yelp", rating: 4.2, ratingScale: 5, ratingCount: 1870 },
    ],
    popularityScore: 85,
  },
  {
    id: "hangari-ktown",
    name: "Hangari Kalguksu",
    latitude: 34.0611,
    longitude: -118.3025,
    address: "3470 W 6th St #200, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Koreatown",
    zip: "90020",
    cuisines: ["Korean"],
    priceLevel: "$$",
    phone: "(213) 738-5312",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("hangari"),
    dishes: [
      {
        name: "Kalguksu",
        description: "Hand-cut knife noodle soup in a mild seafood broth.",
        estimatedPrice: 16,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "Open 24 hours and beloved as late-night comfort food.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.4, ratingScale: 5, ratingCount: 1450 },
      { provider: "yelp", rating: 4.3, ratingScale: 5, ratingCount: 920 },
    ],
    popularityScore: 63,
  },
  {
    id: "yup-dduk-ktown",
    name: "Yup Dduk Koreatown",
    latitude: 34.0645,
    longitude: -118.3037,
    address: "621 S Western Ave, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Koreatown",
    zip: "90005",
    cuisines: ["Korean", "Dessert"],
    priceLevel: "$",
    phone: "(213) 388-0700",
    openingHours: HOURS_LATE,
    photoSeeds: photos("yupdduk"),
    dishes: [
      {
        name: "Rabokki",
        description: "Tteokbokki with ramen noodles in spicy-sweet sauce.",
        estimatedPrice: 14,
        spiceLevel: 2,
        priority: "popular",
        whyOrder: "A late-night Koreatown favorite for a reason.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.2, ratingScale: 5, ratingCount: 780 },
      { provider: "yelp", rating: 4.0, ratingScale: 5, ratingCount: 450 },
    ],
    popularityScore: 52,
  },

  // ----------------------------------------------------------- Downtown LA
  {
    id: "bestia-dtla",
    name: "Bestia",
    latitude: 34.0403,
    longitude: -118.2352,
    address: "2121 E 7th Pl, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Arts District",
    zip: "90021",
    cuisines: ["Italian", "Fine Dining"],
    priceLevel: "$$$$",
    phone: "(213) 514-5724",
    website: "https://bestiala.com",
    openingHours: HOURS_LATE,
    photoSeeds: photos("bestia"),
    dishes: [
      {
        name: "Bone Marrow",
        description: "Roasted bone marrow with rosemary, served with grilled bread.",
        estimatedPrice: 24,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "One of the most iconic openers in LA fine dining.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.6, ratingScale: 5, ratingCount: 4230 },
      { provider: "yelp", rating: 4.3, ratingScale: 5, ratingCount: 2870 },
    ],
    popularityScore: 90,
  },
  {
    id: "guerrilla-tacos-dtla",
    name: "Guerrilla Tacos",
    latitude: 34.0389,
    longitude: -118.2361,
    address: "2000 E 7th St, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Arts District",
    zip: "90021",
    cuisines: ["Mexican", "Cheap Eats"],
    priceLevel: "$$",
    phone: "(213) 375-3300",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("guerrilla"),
    dishes: [
      {
        name: "Sweet Potato Taco",
        description: "Roasted sweet potato, chipotle, pepitas, queso fresco.",
        estimatedPrice: 6,
        spiceLevel: 1,
        priority: "underrated",
        whyOrder: "The vegetarian taco that converts meat-eaters.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.5, ratingScale: 5, ratingCount: 1230 },
      { provider: "yelp", rating: 4.3, ratingScale: 5, ratingCount: 780 },
    ],
    popularityScore: 67,
  },
  {
    id: "howlin-rays-dtla",
    name: "Howlin' Ray's",
    latitude: 34.0616,
    longitude: -118.2384,
    address: "727 N Broadway, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Chinatown",
    zip: "90012",
    cuisines: ["American", "Nashville Hot Chicken"],
    priceLevel: "$$",
    phone: "(213) 935-8399",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("howlinrays"),
    dishes: [
      {
        name: "Hot Chicken Sandwich",
        description: "Nashville-style fried chicken sandwich, choose your spice.",
        estimatedPrice: 13,
        spiceLevel: 3,
        priority: "must_try",
        whyOrder: "Consistently ranked LA's best fried chicken sandwich.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.6, ratingScale: 5, ratingCount: 6780 },
      { provider: "yelp", rating: 4.4, ratingScale: 5, ratingCount: 4120 },
    ],
    popularityScore: 93,
  },

  // ------------------------------------------------------------ Sawtelle / West LA
  {
    id: "tsujita-sawtelle",
    name: "Tsujita LA",
    latitude: 34.0367,
    longitude: -118.4436,
    address: "2057 Sawtelle Blvd, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Sawtelle Japantown",
    zip: "90025",
    cuisines: ["Japanese", "Ramen", "Tsukemen"],
    priceLevel: "$$",
    phone: "(310) 231-7373",
    openingHours: HOURS_LATE,
    photoSeeds: photos("tsujita"),
    dishes: [
      {
        name: "Tsukemen (Dipping Noodles)",
        description: "Thick noodles served with a concentrated dipping broth.",
        estimatedPrice: 15,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "Regarded as one of the best tsukemen outside Japan.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.5, ratingScale: 5, ratingCount: 4980 },
      { provider: "yelp", rating: 4.3, ratingScale: 5, ratingCount: 3450 },
    ],
    popularityScore: 86,
  },
  {
    id: "hokkaido-ramen-santouka-sawtelle",
    name: "Hokkaido Ramen Santouka",
    latitude: 34.0359,
    longitude: -118.4419,
    address: "2130 Sawtelle Blvd, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Sawtelle Japantown",
    zip: "90025",
    cuisines: ["Japanese", "Ramen"],
    priceLevel: "$$",
    phone: "(310) 391-1101",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("santouka"),
    dishes: [
      {
        name: "Shio Ramen",
        description: "Salt-based pork broth ramen, the original Santouka recipe.",
        estimatedPrice: 14,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "The dish that built the chain's reputation across Japan and the US.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.3, ratingScale: 5, ratingCount: 2340 },
      { provider: "yelp", rating: 4.1, ratingScale: 5, ratingCount: 1560 },
    ],
    popularityScore: 66,
  },
  {
    id: "chabuya-sawtelle",
    name: "Chabuya Tokyo Noodle Bar",
    latitude: 34.0374,
    longitude: -118.4441,
    address: "2002 Sawtelle Blvd, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Sawtelle Japantown",
    zip: "90025",
    cuisines: ["Japanese", "Ramen"],
    priceLevel: "$",
    phone: "(310) 444-1147",
    openingHours: HOURS_LATE,
    photoSeeds: photos("chabuya"),
    dishes: [
      {
        name: "Niboshi Ramen",
        description: "Dried sardine-based broth, a sharper, more savory profile.",
        estimatedPrice: 13,
        spiceLevel: 0,
        priority: "adventurous",
        whyOrder: "For ramen fans who've had tonkotsu everywhere else already.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.2, ratingScale: 5, ratingCount: 1120 },
      { provider: "yelp", rating: 4.0, ratingScale: 5, ratingCount: 640 },
    ],
    popularityScore: 48,
  },

  // ------------------------------------------------------- Rounding out variety
  {
    id: "shoney-hi-venice",
    name: "Sonoratown",
    latitude: 34.0454,
    longitude: -118.2506,
    address: "208 E 8th St, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Fashion District",
    zip: "90014",
    cuisines: ["Mexican", "Cheap Eats"],
    priceLevel: "$",
    phone: "(213) 232-5103",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("sonoratown"),
    dishes: [
      {
        name: "Burrito de Adobada",
        description: "Flour tortilla burrito with marinated pork, Sonoran-style.",
        estimatedPrice: 10,
        spiceLevel: 1,
        priority: "must_try",
        whyOrder: "The flour tortillas alone are worth the trip.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.6, ratingScale: 5, ratingCount: 1780 },
      { provider: "yelp", rating: 4.4, ratingScale: 5, ratingCount: 1020 },
    ],
    popularityScore: 75,
  },
  {
    id: "night-market-song-thai",
    name: "Night + Market Song",
    latitude: 34.0857,
    longitude: -118.2851,
    address: "3322 W Sunset Blvd, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Silver Lake",
    zip: "90026",
    cuisines: ["Thai"],
    priceLevel: "$$",
    phone: "(323) 665-5899",
    openingHours: HOURS_LATE,
    photoSeeds: photos("nightmarket"),
    dishes: [
      {
        name: "Crispy Rice Sai Oua",
        description: "Fried rice salad with Northern Thai sausage, herbs, lime.",
        estimatedPrice: 17,
        spiceLevel: 2,
        priority: "must_try",
        whyOrder: "The dish that defines the whole Night + Market menu.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.5, ratingScale: 5, ratingCount: 1670 },
      { provider: "yelp", rating: 4.3, ratingScale: 5, ratingCount: 1230 },
    ],
    popularityScore: 72,
  },
  {
    id: "quarter-sheets-eastside",
    name: "Quarter Sheets Pizza",
    latitude: 34.0781,
    longitude: -118.2601,
    address: "1758 N Virgil Ave, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "East Hollywood",
    zip: "90027",
    cuisines: ["Italian", "Pizza"],
    priceLevel: "$$",
    phone: "(323) 741-8007",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("quartersheets"),
    dishes: [
      {
        name: "Grandma Slice",
        description: "Sicilian-style square slice, olive oil crust, red sauce.",
        estimatedPrice: 6,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "Named one of LA's best new pizzerias.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.7, ratingScale: 5, ratingCount: 540 },
      { provider: "yelp", rating: 4.6, ratingScale: 5, ratingCount: 310 },
    ],
    popularityScore: 79,
  },
  {
    id: "kobawoo-ktown",
    name: "Kobawoo House",
    latitude: 34.0587,
    longitude: -118.3012,
    address: "698 S Vermont Ave, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Koreatown",
    zip: "90005",
    cuisines: ["Korean"],
    priceLevel: "$$",
    phone: "(213) 389-7300",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("kobawoo"),
    dishes: [
      {
        name: "Bossam",
        description: "Boiled pork belly wraps with kimchi and fermented shrimp.",
        estimatedPrice: 36,
        spiceLevel: 1,
        priority: "local_favorite",
        whyOrder: "A Koreatown institution for this exact dish since 1996.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.3, ratingScale: 5, ratingCount: 980 },
      { provider: "yelp", rating: 4.1, ratingScale: 5, ratingCount: 560 },
    ],
    popularityScore: 57,
  },
  {
    id: "north-italia-irvine",
    name: "North Italia",
    latitude: 33.6598,
    longitude: -117.7438,
    address: "13943 Jamboree Rd, Irvine, CA",
    city: "Irvine",
    neighborhood: "Irvine Spectrum",
    zip: "92620",
    cuisines: ["Italian", "Date Night"],
    priceLevel: "$$$",
    phone: "(949) 397-4130",
    openingHours: HOURS_LATE,
    photoSeeds: photos("northitalia"),
    dishes: [
      {
        name: "Truffle Cream Pasta",
        description: "House-made pasta in a black truffle cream sauce.",
        estimatedPrice: 24,
        spiceLevel: 0,
        priority: "popular",
        whyOrder: "The most-photographed pasta on the menu.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.4, ratingScale: 5, ratingCount: 1560 },
      { provider: "yelp", rating: 4.1, ratingScale: 5, ratingCount: 780 },
    ],
    popularityScore: 63,
  },
  {
    id: "cha-cha-chicken-newport",
    name: "Cha Cha Chicken",
    latitude: 33.6033,
    longitude: -117.9289,
    address: "1740 W Balboa Blvd, Newport Beach, CA",
    city: "Newport Beach",
    neighborhood: "Balboa Peninsula",
    zip: "92663",
    cuisines: ["Caribbean", "Cheap Eats"],
    priceLevel: "$",
    phone: "(949) 631-7121",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("chacha"),
    dishes: [
      {
        name: "Jerk Chicken Plate",
        description: "Caribbean jerk-marinated grilled chicken, rice and beans.",
        estimatedPrice: 15,
        spiceLevel: 2,
        priority: "must_try",
        whyOrder: "A beloved beach-town institution near the pier.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.5, ratingScale: 5, ratingCount: 1230 },
      { provider: "yelp", rating: 4.3, ratingScale: 5, ratingCount: 780 },
    ],
    popularityScore: 58,
  },
  {
    id: "cafe-condesa-costa-mesa",
    name: "Cafe Condesa",
    latitude: 33.6417,
    longitude: -117.9187,
    address: "662 Baker St, Costa Mesa, CA",
    city: "Costa Mesa",
    neighborhood: "The Camp",
    zip: "92626",
    cuisines: ["French", "Cafe", "Brunch"],
    priceLevel: "$$",
    phone: "(714) 429-9200",
    openingHours: HOURS_CAFE,
    photoSeeds: photos("condesa"),
    dishes: [
      {
        name: "Croque Madame",
        description: "Grilled ham and gruyere sandwich topped with a fried egg.",
        estimatedPrice: 16,
        spiceLevel: 0,
        priority: "popular",
        whyOrder: "The brunch order that sells out first on weekends.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.5, ratingScale: 5, ratingCount: 640 },
      { provider: "yelp", rating: 4.3, ratingScale: 5, ratingCount: 410 },
    ],
    popularityScore: 51,
  },
  {
    id: "bosscat-newport",
    name: "The Winery Restaurant & Wine Bar",
    latitude: 33.6178,
    longitude: -117.9294,
    address: "3131 W Coast Hwy, Newport Beach, CA",
    city: "Newport Beach",
    neighborhood: "Mariner's Mile",
    zip: "92663",
    cuisines: ["American", "Fine Dining", "Date Night"],
    priceLevel: "$$$$",
    phone: "(949) 999-6622",
    openingHours: HOURS_LATE,
    photoSeeds: photos("winery"),
    dishes: [
      {
        name: "Dry-Aged Ribeye",
        description: "28-day dry-aged ribeye, bone marrow butter.",
        estimatedPrice: 68,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "A special-occasion steak worth the price tag.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.5, ratingScale: 5, ratingCount: 1560 },
      { provider: "yelp", rating: 4.2, ratingScale: 5, ratingCount: 890 },
    ],
    popularityScore: 71,
  },
  {
    id: "hodori-ktown",
    name: "Hodori",
    latitude: 34.0631,
    longitude: -118.2999,
    address: "1001 S Vermont Ave, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Koreatown",
    zip: "90006",
    cuisines: ["Korean"],
    priceLevel: "$",
    phone: "(213) 383-3554",
    openingHours: HOURS_LATE,
    photoSeeds: photos("hodori"),
    dishes: [
      {
        name: "Kimchi Fried Rice",
        description: "Fried rice with aged kimchi and a fried egg on top.",
        estimatedPrice: 13,
        spiceLevel: 1,
        priority: "safe_pick",
        whyOrder: "Open 24 hours — a reliable late-night order every time.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.1, ratingScale: 5, ratingCount: 890 },
      { provider: "yelp", rating: 4.0, ratingScale: 5, ratingCount: 560 },
    ],
    popularityScore: 46,
  },
  {
    id: "cafe-tri-le-irvine",
    name: "Brodard Restaurant",
    latitude: 33.7302,
    longitude: -117.9865,
    address: "9100 Bolsa Ave, Westminster, CA",
    city: "Westminster",
    neighborhood: "Little Saigon",
    zip: "92683",
    cuisines: ["Vietnamese"],
    priceLevel: "$",
    phone: "(714) 892-9990",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("brodard"),
    dishes: [
      {
        name: "Nem Nướng Cuốn",
        description: "Grilled pork sausage spring rolls, wrapped fresh at the table.",
        estimatedPrice: 15,
        spiceLevel: 1,
        priority: "must_try",
        whyOrder: "Widely considered the best nem nướng in Little Saigon.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.4, ratingScale: 5, ratingCount: 3120 },
      { provider: "yelp", rating: 4.2, ratingScale: 5, ratingCount: 2340 },
    ],
    popularityScore: 76,
  },
  {
    id: "sate-noodle-house-westminster",
    name: "Sate Noodle House",
    latitude: 33.7412,
    longitude: -117.9989,
    address: "9200 Bolsa Ave, Westminster, CA",
    city: "Westminster",
    neighborhood: "Little Saigon",
    zip: "92683",
    cuisines: ["Vietnamese", "Chinese"],
    priceLevel: "$",
    phone: "(714) 373-6632",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("satenoodle"),
    dishes: [
      {
        name: "Sate Beef Noodle Soup",
        description: "Spicy peanut-satay beef broth with egg noodles.",
        estimatedPrice: 12,
        spiceLevel: 2,
        priority: "must_try",
        whyOrder: "A cult-favorite bowl unique to this restaurant.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.5, ratingScale: 5, ratingCount: 980 },
      { provider: "yelp", rating: 4.3, ratingScale: 5, ratingCount: 620 },
    ],
    popularityScore: 58,
  },
  {
    id: "afters-ktown",
    name: "Afters Ice Cream",
    latitude: 34.0602,
    longitude: -118.3078,
    address: "3540 W 8th St, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Koreatown",
    zip: "90005",
    cuisines: ["Dessert"],
    priceLevel: "$",
    phone: "(213) 388-5060",
    openingHours: HOURS_LATE,
    photoSeeds: photos("afters"),
    dishes: [
      {
        name: "Milky Bun",
        description: "Warm glazed donut bun stuffed with ice cream.",
        estimatedPrice: 8,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "The dessert that built the whole brand.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.4, ratingScale: 5, ratingCount: 2340 },
      { provider: "yelp", rating: 4.2, ratingScale: 5, ratingCount: 1670 },
    ],
    popularityScore: 74,
  },
  {
    id: "sipology-irvine",
    name: "Sunright Tea Studio",
    latitude: 33.6841,
    longitude: -117.8235,
    address: "71 Fortune Dr, Irvine, CA",
    city: "Irvine",
    neighborhood: "Diamond Jamboree",
    zip: "92618",
    cuisines: ["Taiwanese", "Dessert", "Cafe"],
    priceLevel: "$",
    phone: "(949) 682-3288",
    openingHours: HOURS_CAFE,
    photoSeeds: photos("sunright"),
    dishes: [
      {
        name: "Brown Sugar Boba Milk",
        description: "Fresh milk with house-made brown sugar boba.",
        estimatedPrice: 6.25,
        spiceLevel: 0,
        priority: "popular",
        whyOrder: "Their most-ordered drink by a wide margin.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.4, ratingScale: 5, ratingCount: 780 },
      { provider: "yelp", rating: 4.2, ratingScale: 5, ratingCount: 420 },
    ],
    popularityScore: 55,
  },
  {
    id: "pizzeria-mozza-hancock",
    name: "Pizzeria Mozza",
    latitude: 34.0836,
    longitude: -118.3437,
    address: "641 N Highland Ave, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Hancock Park",
    zip: "90036",
    cuisines: ["Italian", "Pizza", "Date Night"],
    priceLevel: "$$$",
    phone: "(323) 297-0101",
    openingHours: HOURS_LATE,
    photoSeeds: photos("mozza"),
    dishes: [
      {
        name: "Squash Blossom Pizza",
        description: "Wood-fired pizza with squash blossoms, tomato, burrata.",
        estimatedPrice: 22,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "The Nancy Silverton pizza that critics still cite years later.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.5, ratingScale: 5, ratingCount: 5670 },
      { provider: "yelp", rating: 4.2, ratingScale: 5, ratingCount: 3450 },
    ],
    popularityScore: 83,
  },
  {
    id: "sqirl-silverlake",
    name: "Sqirl",
    latitude: 34.0789,
    longitude: -118.2637,
    address: "720 N Virgil Ave, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "East Hollywood",
    zip: "90029",
    cuisines: ["American", "Brunch", "Cafe"],
    priceLevel: "$$",
    phone: "(323) 284-8147",
    openingHours: HOURS_CAFE,
    photoSeeds: photos("sqirl"),
    dishes: [
      {
        name: "Ricotta Toast",
        description: "Housemade ricotta on brioche with seasonal jam.",
        estimatedPrice: 14,
        spiceLevel: 0,
        dietaryTags: ["vegetarian"],
        priority: "must_try",
        whyOrder: "The dish that made this cafe a national brunch destination.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.1, ratingScale: 5, ratingCount: 2340 },
      { provider: "yelp", rating: 3.8, ratingScale: 5, ratingCount: 1890 },
    ],
    popularityScore: 70,
  },
  {
    id: "kismet-los-feliz",
    name: "Kismet",
    latitude: 34.0951,
    longitude: -118.2894,
    address: "4648 Hollywood Blvd, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "Los Feliz",
    zip: "90027",
    cuisines: ["Mediterranean", "Date Night"],
    priceLevel: "$$$",
    phone: "(323) 409-0404",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("kismet"),
    dishes: [
      {
        name: "Caramelized Shallot Pasta",
        description: "Rigatoni with caramelized shallots, herbs, breadcrumbs.",
        estimatedPrice: 26,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "The most talked-about pasta dish in LA the year it opened.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.5, ratingScale: 5, ratingCount: 1230 },
      { provider: "yelp", rating: 4.3, ratingScale: 5, ratingCount: 780 },
    ],
    popularityScore: 77,
  },
  {
    id: "kato-westadams",
    name: "Kato",
    latitude: 34.0261,
    longitude: -118.3437,
    address: "4720 W Washington Blvd, Los Angeles, CA",
    city: "Los Angeles",
    neighborhood: "West Adams",
    zip: "90016",
    cuisines: ["Taiwanese", "Fine Dining"],
    priceLevel: "$$$$",
    phone: "(323) 590-8085",
    website: "https://katorestaurant.com",
    openingHours: HOURS_STANDARD,
    photoSeeds: photos("kato"),
    dishes: [
      {
        name: "Tasting Menu",
        description: "Chef Jon Yao's Taiwanese-American tasting menu, seasonal.",
        estimatedPrice: 225,
        spiceLevel: 1,
        priority: "must_try",
        whyOrder: "Michelin-starred, widely regarded as one of LA's best tables.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.7, ratingScale: 5, ratingCount: 780 },
      { provider: "yelp", rating: 4.5, ratingScale: 5, ratingCount: 340 },
    ],
    popularityScore: 81,
  },
  {
    id: "moo-moo-korean-bbq-irvine",
    name: "Genwa Korean BBQ Irvine",
    latitude: 33.6521,
    longitude: -117.7469,
    address: "2700 Alton Pkwy Ste 100, Irvine, CA",
    city: "Irvine",
    neighborhood: "Irvine Spectrum",
    zip: "92606",
    cuisines: ["Korean", "Korean BBQ", "Date Night"],
    priceLevel: "$$$",
    phone: "(949) 891-0292",
    openingHours: HOURS_LATE,
    photoSeeds: photos("genwa"),
    dishes: [
      {
        name: "Genwa Combo",
        description: "Prime short rib, brisket, and pork belly grilled tableside.",
        estimatedPrice: 55,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "The most balanced sampler for a first-time table.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.4, ratingScale: 5, ratingCount: 1120 },
      { provider: "yelp", rating: 4.2, ratingScale: 5, ratingCount: 670 },
    ],
    popularityScore: 64,
  },
  {
    id: "portos-costa-mesa",
    name: "Porto's Bakery & Cafe",
    latitude: 33.6739,
    longitude: -117.9143,
    address: "3821 S Bristol St, Costa Mesa, CA",
    city: "Costa Mesa",
    neighborhood: "South Coast",
    zip: "92626",
    cuisines: ["Cuban", "Bakery", "Cheap Eats"],
    priceLevel: "$",
    phone: "(714) 428-4133",
    openingHours: HOURS_CAFE,
    photoSeeds: photos("portos"),
    dishes: [
      {
        name: "Potato Ball",
        description: "Mashed potato stuffed with seasoned ground beef, fried.",
        estimatedPrice: 2.25,
        spiceLevel: 0,
        priority: "must_try",
        whyOrder: "The single most-ordered item chain-wide.",
      },
    ],
    sources: [
      { provider: "google", rating: 4.6, ratingScale: 5, ratingCount: 8920 },
      { provider: "yelp", rating: 4.4, ratingScale: 5, ratingCount: 5670 },
    ],
    popularityScore: 92,
  },
];

/**
 * Full mock dataset: the 52 hand-authored restaurants above (real dish
 * guides, curated "why order" copy) plus ~260 procedurally-generated ones
 * (see generated.ts) so the map/discover feel populated at real density
 * across many more OC/LA neighborhoods.
 */
export const mockRestaurants: MockRestaurantSeed[] = [...handCraftedRestaurants, ...generatedRestaurants];

export function photoUrl(seed: string): string {
  return `https://picsum.photos/seed/${seed}/800/600`;
}
